"""init

Revision ID: 3d1fe30b4fb5
Revises: 6129c613d266
Create Date: 2026-02-25 20:53:52.566592

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '3d1fe30b4fb5'
down_revision: str | Sequence[str] | None = '6129c613d266'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
