"""empty message

Revision ID: 8bc617db9f53
Revises: 3d1fe30b4fb5
Create Date: 2026-02-25 21:39:47.759162

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '8bc617db9f53'
down_revision: str | Sequence[str] | None = '3d1fe30b4fb5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
