"""Finalized Template

Revision ID: bac2d7ef12ca
Revises: 8bc617db9f53
Create Date: 2026-02-25 21:40:28.721963

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'bac2d7ef12ca'
down_revision: str | Sequence[str] | None = '8bc617db9f53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
